// Curated Portuguese glosses for English lemmas of three characters or fewer.
//
// The reverse (English-front) decks read their Portuguese words from the
// `translations` array on the English Wiktionary entries, which is thin and
// noisy for very frequent short words (`can` -> `lata`, `go` -> `dizer`). This
// map is authoritative for those lemmas and fully replaces the extracted
// translations. Regenerate the deck after editing.

/** Per-target-language tables; a language with no table keeps the pipeline's
 *  own translations. */
export const ENGLISH_SHORT_WORD_GLOSSES: Record<string, ReadonlyMap<string, readonly string[]>> = {
  pt: new Map<string, readonly string[]>([
    ['I', ['eu']],
    ['a', ['um', 'uma']],
    ['act', ['ato', 'agir']],
    ['age', ['idade']],
    ['ago', ['atrás']],
    ['aid', ['ajuda']],
    ['aim', ['objetivo']],
    ['air', ['ar']],
    ['all', ['todo', 'toda']],
    ['an', ['um', 'uma']],
    ['and', ['e']],
    ['any', ['qualquer']],
    ['arm', ['braço']],
    ['art', ['arte']],
    ['as', ['como']],
    ['ask', ['perguntar', 'pedir']],
    ['at', ['em']],
    ['bad', ['mau', 'ruim']],
    ['bag', ['bolsa', 'saco']],
    ['ban', ['proibir']],
    ['bar', ['bar']],
    ['be', ['ser', 'estar']],
    ['bed', ['cama']],
    ['bet', ['apostar']],
    ['bid', ['lance', 'oferta']],
    ['big', ['grande']],
    ['box', ['caixa']],
    ['boy', ['menino']],
    ['bug', ['inseto', 'erro']],
    ['bum', ['vagabundo']],
    ['bus', ['ônibus']],
    ['but', ['mas']],
    ['buy', ['comprar']],
    ['by', ['por']],
    ['bye', ['tchau']],
    ['can', ['poder']],
    ['car', ['carro']],
    ['cat', ['gato']],
    ['cow', ['vaca']],
    ['cry', ['chorar']],
    ['cup', ['xícara', 'copo']],
    ['cut', ['cortar']],
    ['dad', ['pai']],
    ['day', ['dia']],
    ['die', ['morrer']],
    ['do', ['fazer']],
    ['dog', ['cachorro', 'cão']],
    ['dry', ['seco']],
    ['due', ['devido']],
    ['ear', ['orelha']],
    ['eat', ['comer']],
    ['egg', ['ovo']],
    ['end', ['fim']],
    ['era', ['era']],
    ['eye', ['olho']],
    ['fag', ['cigarro']],
    ['fan', ['fã', 'ventilador']],
    ['fat', ['gordo', 'gordura']],
    ['fee', ['taxa']],
    ['few', ['poucos']],
    ['fit', ['caber']],
    ['fix', ['consertar']],
    ['fly', ['voar', 'mosca']],
    ['for', ['para', 'por']],
    ['fun', ['diversão']],
    ['gap', ['lacuna']],
    ['gas', ['gás']],
    ['gay', ['gay']],
    ['get', ['conseguir', 'obter']],
    ['gig', ['show']],
    ['go', ['ir']],
    ['god', ['deus']],
    ['gun', ['arma']],
    ['guy', ['cara', 'sujeito']],
    ['he', ['ele']],
    ['her', ['dela', 'seu']],
    ['hey', ['ei']],
    ['hi', ['oi']],
    ['hip', ['quadril']],
    ['his', ['dele', 'seu']],
    ['hit', ['bater']],
    ['hot', ['quente']],
    ['how', ['como']],
    ['i', ['eu']],
    ['ice', ['gelo']],
    ['if', ['se']],
    ['ill', ['doente']],
    ['in', ['em']],
    ['is', ['é']],
    ['it', ['isto']],
    ['its', ['seu']],
    ['jam', ['geleia']],
    ['job', ['trabalho']],
    ['joy', ['alegria']],
    ['key', ['chave']],
    ['kid', ['criança']],
    ['kit', ['kit']],
    ['lad', ['rapaz']],
    ['law', ['lei']],
    ['lay', ['deitar']],
    ['leg', ['perna']],
    ['let', ['deixar']],
    ['lie', ['mentira', 'deitar']],
    ['lot', ['muito']],
    ['low', ['baixo']],
    ['mad', ['louco', 'bravo']],
    ['man', ['homem']],
    ['map', ['mapa']],
    ['may', ['maio', 'poder']],
    ['me', ['me']],
    ['mum', ['mãe']],
    ['my', ['meu', 'minha']],
    ['net', ['rede']],
    ['new', ['novo']],
    ['no', ['não']],
    ['nor', ['nem']],
    ['not', ['não']],
    ['now', ['agora']],
    ['nut', ['noz', 'castanha']],
    ['odd', ['estranho', 'ímpar']],
    ['of', ['de']],
    ['oh', ['oh']],
    ['oil', ['óleo']],
    ['ok', ['ok']],
    ['old', ['velho']],
    ['on', ['em']],
    ['one', ['um', 'uma']],
    ['or', ['ou']],
    ['our', ['nosso']],
    ['out', ['fora']],
    ['owe', ['dever']],
    ['own', ['próprio']],
    ['pay', ['pagar']],
    ['pea', ['ervilha']],
    ['pet', ['animal de estimação']],
    ['pig', ['porco']],
    ['pit', ['poço']],
    ['pop', ['estourar']],
    ['pot', ['panela']],
    ['pub', ['bar']],
    ['put', ['colocar']],
    ['rat', ['rato']],
    ['raw', ['cru']],
    ['red', ['vermelho']],
    ['row', ['fila', 'linha']],
    ['run', ['correr']],
    ['sad', ['triste']],
    ['say', ['dizer']],
    ['sea', ['mar']],
    ['see', ['ver']],
    ['set', ['conjunto', 'definir']],
    ['sex', ['sexo']],
    ['she', ['ela']],
    ['sin', ['pecado']],
    ['sir', ['senhor']],
    ['sit', ['sentar']],
    ['six', ['seis']],
    ['sky', ['céu']],
    ['so', ['então']],
    ['son', ['filho']],
    ['sum', ['soma']],
    ['sun', ['sol']],
    ['tag', ['etiqueta']],
    ['tap', ['torneira', 'bater']],
    ['tax', ['imposto']],
    ['tea', ['chá']],
    ['ten', ['dez']],
    ['the', ['o', 'a']],
    ['tie', ['gravata', 'empatar']],
    ['tin', ['lata', 'estanho']],
    ['tip', ['dica', 'gorjeta']],
    ['to', ['para']],
    ['toe', ['dedo do pé']],
    ['ton', ['tonelada']],
    ['too', ['também']],
    ['top', ['topo', 'cima']],
    ['try', ['tentar']],
    ['two', ['dois']],
    ['up', ['acima']],
    ['us', ['nós']],
    ['use', ['usar']],
    ['van', ['van']],
    ['war', ['guerra']],
    ['way', ['caminho', 'jeito']],
    ['we', ['nós']],
    ['web', ['teia', 'rede']],
    ['wet', ['molhado']],
    ['who', ['quem']],
    ['why', ['por que']],
    ['win', ['ganhar']],
    ['yes', ['sim']],
    ['yet', ['ainda']],
    ['you', ['você', 'tu']],
  ]),
};

