// Curated English glosses for French lemmas of four characters or fewer.
//
// These high-frequency short words are where the Wiktionary-derived pipeline is
// weakest: raw sense links drag in stray letters, abbreviations, proper nouns,
// English code-switches and conjugated forms. For every lemma here this map is
// authoritative and fully replaces the Wiktionary glosses. An empty list drops
// the lemma from the deck, which is how letters and abbreviations are removed.
//
// Generated from a curated table; regenerate the deck after editing.

export const FRENCH_SHORT_WORD_MAX_LENGTH = 4;

export const FRENCH_SHORT_WORD_GLOSSES: ReadonlyMap<string, readonly string[]> = new Map<
  string,
  readonly string[]
>([
  ['y', ['there']],
  ['à', ['to', 'at']],
  ['ah', ['ah']],
  ['an', ['year']],
  ['au', ['to the', 'at the']],
  ['ce', ['this', 'that']],
  ['de', ['of', 'from']],
  ['du', ['of the', 'some']],
  ['en', ['in', 'of it']],
  ['et', ['and']],
  ['il', ['he', 'it']],
  ['je', ['i']],
  ['la', ['the', 'her']],
  ['le', ['the', 'him']],
  ['là', ['there']],
  ['me', ['me', 'myself']],
  ['ne', ['not']],
  ['ni', ['nor']],
  ['no', ['no']],
  ['nu', ['naked']],
  ['on', ['one', 'we']],
  ['or', ['gold']],
  ['os', ['bone']],
  ['ou', ['or']],
  ['où', ['where']],
  ['sa', ['his', 'her']],
  ['se', ['oneself']],
  ['si', ['if', 'yes']],
  ['ta', ['your']],
  ['te', ['you', 'yourself']],
  ['tu', ['you']],
  ['un', ['a', 'one']],
  ['ça', ['that', 'it']],
  ['air', ['air']],
  ['ami', ['friend']],
  ['arc', ['bow', 'arch']],
  ['art', ['art']],
  ['aux', ['to the', 'at the']],
  ['axe', ['axis']],
  ['bac', ['ferry', 'bin']],
  ['bar', ['bar']],
  ['bas', ['low', 'bottom']],
  ['bel', ['beautiful']],
  ['bio', ['organic']],
  ['bol', ['bowl']],
  ['bon', ['good']],
  ['bus', ['bus']],
  ['but', ['goal', 'aim']],
  ['cap', ['cape', 'heading']],
  ['car', ['because']],
  ['cas', ['case']],
  ['cet', ['this', 'that']],
  ['clé', ['key']],
  ['col', ['collar']],
  ['cru', ['raw']],
  ['des', ['of the', 'some']],
  ['dix', ['ten']],
  ['don', ['gift']],
  ['dos', ['back']],
  ['dur', ['hard', 'tough']],
  ['dès', ['from', 'since']],
  ['eau', ['water']],
  ['est', ['east']],
  ['euh', ['uh']],
  ['fan', ['fan']],
  ['fer', ['iron']],
  ['feu', ['fire']],
  ['fil', ['thread']],
  ['fin', ['end']],
  ['foi', ['faith']],
  ['fou', ['crazy']],
  ['gay', ['gay']],
  ['gaz', ['gas']],
  ['ici', ['here']],
  ['ils', ['they']],
  ['jeu', ['game']],
  ['job', ['job']],
  ['jus', ['juice']],
  ['lac', ['lake']],
  ['las', ['tired']],
  ['lis', ['lily']],
  ['lit', ['bed']],
  ['loi', ['law']],
  ['lot', ['lot']],
  ['lui', ['him', 'her']],
  ['mai', ['may']],
  ['mal', ['bad', 'harm']],
  ['mec', ['guy']],
  ['mer', ['sea']],
  ['mes', ['my']],
  ['moi', ['me']],
  ['mon', ['my']],
  ['mot', ['word']],
  ['mur', ['wall']],
  ['net', ['clean', 'clear']],
  ['nez', ['nose']],
  ['nom', ['name']],
  ['non', ['no']],
  ['nul', ['useless', 'zero']],
  ['oui', ['yes']],
  ['par', ['by', 'through']],
  ['pas', ['not']],
  ['peu', ['little', 'few']],
  ['pis', ['worse']],
  ['pop', ['pop']],
  ['pot', ['pot']],
  ['pro', ['pro']],
  ['pré', ['meadow']],
  ['pub', ['ad']],
  ['pur', ['pure']],
  ['que', ['that', 'which']],
  ['qui', ['who', 'which']],
  ['riz', ['rice']],
  ['roi', ['king']],
  ['rue', ['street']],
  ['sac', ['bag']],
  ['sec', ['dry']],
  ['sel', ['salt']],
  ['ses', ['his', 'her']],
  ['six', ['six']],
  ['ski', ['ski']],
  ['soi', ['oneself']],
  ['sol', ['ground', 'floor']],
  ['son', ['his', 'her']],
  ['sud', ['south']],
  ['sur', ['on']],
  ['sûr', ['sure']],
  ['tas', ['pile']],
  ['tel', ['such']],
  ['tes', ['your']],
  ['thé', ['tea']],
  ['tir', ['shooting']],
  ['toi', ['you']],
  ['ton', ['your']],
  ['top', ['top']],
  ['tôt', ['early']],
  ['une', ['a', 'one']],
  ['uni', ['united', 'plain']],
  ['van', ['van']],
  ['via', ['via']],
  ['vie', ['life']],
  ['vin', ['wine']],
  ['vis', ['screw']],
  ['vol', ['theft', 'flight']],
  ['vue', ['view']],
  ['âge', ['age']],
  ['âgé', ['old', 'elderly']],
  ['âme', ['soul']],
  ['ère', ['era']],
  ['élu', ['elected', 'elected official']],
  ['été', ['summer']],
  ['île', ['island']],
  ['œil', ['eye']],
  ['abbé', ['abbot']],
  ['abri', ['shelter']],
  ['abus', ['abuse']],
  ['acte', ['act']],
  ['afin', ['in order to']],
  ['agir', ['to act']],
  ['aide', ['help']],
  ['aile', ['wing']],
  ['aise', ['ease']],
  ['amie', ['friend']],
  ['ange', ['angel']],
  ['août', ['august']],
  ['arme', ['weapon']],
  ['aube', ['dawn']],
  ['auto', ['car']],
  ['avec', ['with']],
  ['avis', ['opinion']],
  ['baie', ['bay', 'berry']],
  ['bail', ['lease']],
  ['bain', ['bath']],
  ['banc', ['bench']],
  ['base', ['base', 'basis']],
  ['beau', ['beautiful']],
  ['bien', ['well', 'good']],
  ['bleu', ['blue']],
  ['bloc', ['block']],
  ['blog', ['blog']],
  ['bois', ['wood']],
  ['bord', ['edge']],
  ['boss', ['boss']],
  ['bout', ['end', 'tip']],
  ['bras', ['arm']],
  ['bref', ['brief']],
  ['brut', ['raw', 'gross']],
  ['bébé', ['baby']],
  ['bête', ['animal', 'stupid']],
  ['café', ['coffee', 'café']],
  ['camp', ['camp']],
  ['case', ['box', 'compartment']],
  ['cave', ['cellar', 'basement']],
  ['ceci', ['this']],
  ['cela', ['that']],
  ['cent', ['hundred']],
  ['chat', ['cat']],
  ['chef', ['chief', 'chef']],
  ['cher', ['dear', 'expensive']],
  ['chez', ['at', 'at someone\'s place']],
  ['choc', ['shock']],
  ['ciel', ['sky']],
  ['cinq', ['five']],
  ['cité', ['city']],
  ['clan', ['clan']],
  ['clip', ['clip']],
  ['club', ['club']],
  ['code', ['code']],
  ['coin', ['corner']],
  ['cool', ['cool']],
  ['cote', ['rating']],
  ['coup', ['blow', 'hit']],
  ['cour', ['courtyard']],
  ['coût', ['cost']],
  ['cuir', ['leather']],
  ['côte', ['coast', 'slope']],
  ['côté', ['side']],
  ['cœur', ['heart']],
  ['dame', ['lady']],
  ['dans', ['in']],
  ['date', ['date']],
  ['demi', ['half']],
  ['deux', ['two']],
  ['dieu', ['god']],
  ['dire', ['to say', 'to tell']],
  ['donc', ['so', 'therefore']],
  ['dont', ['whose', 'of which']],
  ['dose', ['dose']],
  ['doux', ['soft', 'sweet']],
  ['défi', ['challenge']],
  ['déjà', ['already']],
  ['déçu', ['disappointed']],
  ['elle', ['she', 'her']],
  ['euro', ['euro']],
  ['face', ['face']],
  ['faim', ['hunger']],
  ['fait', ['fact']],
  ['faux', ['false']],
  ['fier', ['proud']],
  ['file', ['line', 'queue']],
  ['film', ['film', 'movie']],
  ['fils', ['son']],
  ['fine', ['fine', 'thin']],
  ['fini', ['finished']],
  ['fixe', ['fixed']],
  ['flux', ['flow']],
  ['foie', ['liver']],
  ['fois', ['time', 'occurrence']],
  ['fond', ['bottom', 'background']],
  ['foot', ['football']],
  ['fort', ['strong']],
  ['four', ['oven']],
  ['fuir', ['to flee']],
  ['fête', ['party', 'holiday']],
  ['gain', ['gain']],
  ['gare', ['station']],
  ['gars', ['guy']],
  ['gens', ['people']],
  ['golf', ['golf']],
  ['goût', ['taste']],
  ['gras', ['fat']],
  ['grec', ['greek']],
  ['gris', ['grey']],
  ['gros', ['big', 'fat']],
  ['gêne', ['embarrassment']],
  ['haha', ['haha']],
  ['hall', ['hall']],
  ['haut', ['high']],
  ['hein', ['huh']],
  ['hier', ['yesterday']],
  ['hors', ['outside']],
  ['huit', ['eight']],
  ['hâte', ['haste']],
  ['idée', ['idea']],
  ['info', ['info', 'news']],
  ['issu', ['from', 'resulting']],
  ['jazz', ['jazz']],
  ['jean', ['jeans']],
  ['joie', ['joy']],
  ['joli', ['pretty']],
  ['joue', ['cheek']],
  ['jour', ['day']],
  ['juge', ['judge']],
  ['juif', ['jewish']],
  ['juin', ['june']],
  ['jury', ['jury']],
  ['lait', ['milk']],
  ['leur', ['their', 'them']],
  ['lien', ['link']],
  ['lieu', ['place']],
  ['lion', ['lion']],
  ['lire', ['to read']],
  ['logo', ['logo']],
  ['loin', ['far']],
  ['long', ['long']],
  ['lors', ['then']],
  ['loup', ['wolf']],
  ['lune', ['moon']],
  ['luxe', ['luxury']],
  ['mail', ['email']],
  ['main', ['hand']],
  ['mais', ['but']],
  ['mari', ['husband']],
  ['mars', ['march']],
  ['menu', ['menu']],
  ['midi', ['noon']],
  ['mien', ['mine']],
  ['mine', ['mine', 'look']],
  ['mini', ['mini']],
  ['mise', ['bet', 'setting']],
  ['mode', ['fashion', 'mode']],
  ['mois', ['month']],
  ['mont', ['mount']],
  ['mort', ['dead', 'death']],
  ['moto', ['motorcycle']],
  ['mère', ['mother']],
  ['même', ['same', 'even']],
  ['neuf', ['new', 'nine']],
  ['noir', ['black']],
  ['nord', ['north']],
  ['note', ['note']],
  ['nous', ['we', 'us']],
  ['noël', ['christmas']],
  ['nuit', ['night']],
  ['onze', ['eleven']],
  ['ours', ['bear']],
  ['page', ['page']],
  ['paie', ['pay']],
  ['pain', ['bread']],
  ['paix', ['peace']],
  ['papa', ['dad']],
  ['pape', ['pope']],
  ['parc', ['park']],
  ['part', ['share']],
  ['paye', ['pay']],
  ['pays', ['country']],
  ['peau', ['skin']],
  ['peur', ['fear']],
  ['pied', ['foot']],
  ['pile', ['battery', 'pile']],
  ['pire', ['worse']],
  ['plan', ['plan']],
  ['plat', ['dish', 'flat']],
  ['plus', ['more']],
  ['poil', ['hair']],
  ['pont', ['bridge']],
  ['port', ['port']],
  ['pose', ['pose']],
  ['post', ['post']],
  ['pote', ['buddy']],
  ['pour', ['for']],
  ['prix', ['price']],
  ['prof', ['teacher']],
  ['près', ['near']],
  ['prêt', ['ready']],
  ['puis', ['then']],
  ['père', ['father']],
  ['pôle', ['pole']],
  ['quai', ['platform', 'quay']],
  ['quel', ['which', 'what']],
  ['quoi', ['what']],
  ['race', ['race']],
  ['rage', ['rage']],
  ['rang', ['row', 'rank']],
  ['rare', ['rare']],
  ['reçu', ['receipt']],
  ['rien', ['nothing']],
  ['rire', ['to laugh']],
  ['rive', ['bank', 'shore']],
  ['robe', ['dress']],
  ['rock', ['rock']],
  ['rond', ['round']],
  ['rose', ['pink', 'rose']],
  ['roue', ['wheel']],
  ['réel', ['real']],
  ['rêve', ['dream']],
  ['rôle', ['role']],
  ['sage', ['wise', 'good']],
  ['sale', ['dirty']],
  ['sang', ['blood']],
  ['sans', ['without']],
  ['sauf', ['except']],
  ['sein', ['breast']],
  ['sens', ['sense', 'meaning']],
  ['sept', ['seven']],
  ['seul', ['alone', 'only']],
  ['sexe', ['sex']],
  ['sexy', ['sexy']],
  ['show', ['show']],
  ['site', ['site', 'website']],
  ['soin', ['care']],
  ['soir', ['evening']],
  ['solo', ['solo']],
  ['sort', ['fate', 'spell']],
  ['sous', ['under']],
  ['star', ['star']],
  ['sœur', ['sister']],
  ['tant', ['so much']],
  ['tape', ['tap', 'pat']],
  ['tard', ['late']],
  ['taux', ['rate']],
  ['taxe', ['tax']],
  ['taxi', ['taxi']],
  ['test', ['test']],
  ['toit', ['roof']],
  ['tome', ['volume']],
  ['tort', ['wrong']],
  ['tour', ['turn', 'tower']],
  ['tous', ['all']],
  ['tout', ['all', 'everything']],
  ['trop', ['too much']],
  ['trou', ['hole']],
  ['truc', ['thing']],
  ['très', ['very']],
  ['tube', ['tube']],
  ['tuer', ['to kill']],
  ['type', ['type', 'guy']],
  ['télé', ['tv']],
  ['tête', ['head']],
  ['vent', ['wind']],
  ['vers', ['toward']],
  ['vert', ['green']],
  ['vice', ['vice']],
  ['vide', ['empty']],
  ['vite', ['fast', 'quickly']],
  ['vive', ['lively', 'long live']],
  ['voie', ['way', 'track']],
  ['voir', ['to see']],
  ['voix', ['voice']],
  ['vote', ['vote']],
  ['vous', ['you']],
  ['vrai', ['true']],
  ['vélo', ['bike']],
  ['zone', ['zone', 'area']],
  ['zéro', ['zero']],
  ['égal', ['equal']],
  ['épée', ['sword']],
  ['état', ['state']],
  ['être', ['to be']],
  // Letters, abbreviations, proper nouns and conjugated forms: dropped.
  ['a', []], ['c', []], ['d', []], ['g', []], ['k', []], ['m', []],
  ['o', []], ['p', []], ['q', []], ['t', []], ['ac', []], ['al', []],
  ['as', []], ['ca', []], ['ch', []], ['ci', []], ['cv', []], ['do', []],
  ['dû', []], ['ed', []], ['ex', []], ['fi', []], ['go', []], ['ha', []],
  ['hé', []], ['li', []], ['mi', []], ['né', []], ['oh', []], ['pp', []],
  ['pu', []], ['qu', []], ['to', []], ['tv', []], ['us', []], ['vu', []],
  ['age', []], ['bah', []], ['ben', []], ['bob', []], ['box', []], ['boy', []],
  ['con', []], ['cou', []], ['cul', []], ['dan', []], ['der', []], ['dit', []],
  ['duc', []], ['duo', []], ['fac', []], ['hop', []], ['lol', []], ['los', []],
  ['mac', []], ['man', []], ['mio', []], ['roy', []], ['san', []], ['usa', []],
  ['val', []], ['vit', []], ['web', []], ['aimé', []], ['armé', []], ['aura', []],
  ['baby', []], ['basé', []], ['bill', []], ['bite', []], ['delà', []], ['etre', []],
  ['girl', []], ['jeté', []], ['joué', []], ['jugé', []], ['live', []], ['mali', []],
  ['marc', []], ['mark', []], ['mets', []], ['news', []], ['nice', []], ['open', []],
  ['peut', []], ['pris', []], ['pute', []], ['raté', []], ['rené', []], ['soit', []],
  ['stop', []], ['tire', []], ['tiré', []], ['tony', []], ['viol', []], ['vues', []],
  ['vécu', []], ['élus', []], ['êtes', []],
]);
