// Curated English glosses for Portuguese lemmas of four characters or fewer.
//
// These high-frequency short words are where the Wiktionary-derived pipeline is
// weakest: raw sense links drag in topic labels (`anatomia` -> `anatomy`),
// grammar labels (`masculino` -> `masculine`), stray letters and proper nouns.
// For every lemma here this map is authoritative and fully replaces the
// Wiktionary glosses. An empty list drops the lemma from the deck, which is how
// noise is removed. Regenerate the deck after editing.

export const PORTUGUESE_SHORT_WORD_MAX_LENGTH = 4;

export const PORTUGUESE_SHORT_WORD_GLOSSES: ReadonlyMap<string, readonly string[]> = new Map<
  string,
  readonly string[]
>([
  ['a', ['to', 'at']],
  ['abc', []],
  ['abre', []],
  ['acha', ['billet', 'battle axe']],
  ['acho', []],
  ['adam', []],
  ['afro', ['afro', 'african']],
  ['age', []],
  ['agir', ['do', 'act', 'function', 'perform', 'conduct', 'behave']],
  ['ah', ['ah']],
  ['ai', ['ouch', 'oh']],
  ['aids', []],
  ['al', ['everything', 'rest', 'other', 'another']],
  ['alan', []],
  ['alex', []],
  ['algo', ['something']],
  ['ali', ['there']],
  ['all', []],
  ['alma', ['soul']],
  ['alta', ['discharge', 'rise', 'increase']],
  ['alto', ['high', 'tall', 'loud']],
  ['alvo', ['white', 'pure', 'target', 'goal', 'object', 'criticism']],
  ['além', ['there', 'over there', 'beyond', 'afterlife']],
  ['alô', ['hello', 'greet']],
  ['am', []],
  ['ama', ['nurse', 'housekeeper', 'governess']],
  ['amam', []],
  ['amar', ['love']],
  ['amei', []],
  ['amo', ['master', 'boss', 'internet']],
  ['amor', ['love']],
  ['amy', []],
  ['an', []],
  ['ana', []],
  ['and', []],
  ['anda', ['stilt', 'procession']],
  ['ando', []],
  ['anel', ['ring', 'anus', 'ringpiece', 'annulus']],
  ['anjo', ['angel', 'good', 'person']],
  ['anna', []],
  ['anne', []],
  ['ano', ['year']],
  ['anos', []],
  ['anti', ['anti']],
  ['ao', ['to the', 'at the']],
  ['aos', ['to the']],
  ['app', ['app']],
  ['após', ['after', 'past']],
  ['aqui', ['here']],
  ['ar', ['air', 'look']],
  ['arco', ['arc', 'curve', 'arch', 'bow', 'rod', 'play']],
  ['are', ['are']],
  ['arma', ['weapon']],
  ['art', []],
  ['arte', ['art']],
  ['as', ['the']],
  ['asas', []],
  ['at', []],
  ['ate', []],
  ['ato', ['act']],
  ['ator', ['actor']],
  ['atos', []],
  ['atua', []],
  ['até', ['until', 'up to']],
  ['aula', ['classroom', 'lecture', 'lesson', 'class', 'auditorium']],
  ['auto', ['public', 'deed', 'ceremony', 'auto', 'act', 'exhibit']],
  ['av', []],
  ['ave', ['bird']],
  ['aves', []],
  ['avó', ['grandmother', 'grandparent']],
  ['avô', ['grandfather', 'grandparent']],
  ['azul', ['blue']],
  ['aço', ['steel', 'strong', 'resistent', 'will', 'disposition', 'patience']],
  ['ação', ['action', 'lawsuit', 'share', 'fight', 'engagement']],
  ['aí', ['there', 'second person', 'then', 'case', 'situation', 'yeah']],
  ['b', []],
  ['ba', []],
  ['baby', []],
  ['back', []],
  ['bad', []],
  ['bala', ['bullet', 'projectile', 'ammunition', 'candy', 'sweet', 'ecstasy']],
  ['bar', ['pub', 'bar']],
  ['base', ['basis', 'base', 'groundwork', 'foundation']],
  ['bate', []],
  ['bbc', []],
  ['be', []],
  ['bebe', []],
  ['bebê', []],
  ['bela', []],
  ['belo', ['beautiful', 'attractive']],
  ['bem', ['well']],
  ['ben', []],
  ['bens', ['goods', 'estate']],
  ['best', ['bestie']],
  ['bico', ['beak', 'bill', 'snout', 'rostrum', 'poultry', 'mouth']],
  ['big', []],
  ['bill', []],
  ['blog', []],
  ['boa', ['interesting', 'story', 'joke', 'news', 'good one', 'well done']],
  ['boas', ['hey']],
  ['bob', ['curler', 'hair roller', 'hair curler']],
  ['boca', ['mouth', 'brim', 'bottle', 'container', 'burner', 'ring']],
  ['bola', ['ball', 'sphere', 'derogatory', 'fat', 'person', 'testicle']],
  ['bolo', ['cake', 'dessert', 'dough', 'snack', 'bunch', 'heap']],
  ['bom', ['good']],
  ['bons', []],
  ['book', []],
  ['boy', ['office boy', 'boyfriend', 'derogatory', 'upper-class', 'man']],
  ['br', ['internet']],
  ['by', []],
  ['c', ['internet', 'text messaging']],
  ['ca', ['because']],
  ['cabe', []],
  ['cabo', ['cape', 'moments', 'event', 'corporal', 'head man', 'cable']],
  ['cada', ['each']],
  ['cadê', ['where', 'is']],
  ['café', ['coffee']],
  ['cai', []],
  ['caio', []],
  ['cair', ['fall', 'fall down', 'drop', 'collapse', 'suit', 'be']],
  ['caiu', []],
  ['cala', []],
  ['cama', ['bed']],
  ['can', []],
  ['cana', ['cane', 'reed', 'plant', 'fibrous', 'elongate', 'stalk']],
  ['caos', ['chaos']],
  ['capa', ['cloak', 'cape', 'cover', 'front cover', 'front page', 'jacket']],
  ['cara', ['face', 'heads', 'resemblance', 'appearance', 'look', 'man']],
  ['carl', []],
  ['caro', ['valued', 'dear', 'loved', 'lovable', 'price', 'expensive']],
  ['casa', ['house', 'home']],
  ['caso', ['if', 'case', 'grammatical case', 'tale', 'story', 'account']],
  ['caça', ['hunting', 'hunt', 'game', 'fighter']],
  ['cc', []],
  ['cd', []],
  ['ce', []],
  ['cedo', ['early', 'before', 'soon', 'start']],
  ['cego', ['blind', 'blinded', 'dull', 'impartial', 'high', 'stoned']],
  ['cem', ['one hundred']],
  ['cena', ['scene', 'stage', 'thing']],
  ['chá', ['tea plant', 'tea', 'afternoon', 'meal', 'drug', 'infusing']],
  ['chão', ['ground', 'floor']],
  ['cia', []],
  ['cima', ['top', 'summit']],
  ['city', []],
  ['club', []],
  ['cm', []],
  ['co', []],
  ['coca', ['coca', 'erythroxylum coca', 'coke']],
  ['coco', ['coconut', 'head', 'testicle', 'dance', 'alagoas', 'coccus']],
  ['cola', ['glue', 'paste', 'adhesive', 'tail', 'track', 'trail']],
  ['colo', ['lap', 'neck', 'collum', 'cervix', 'gap', 'channel']],
  ['com', ['with']],
  ['coma', ['coma', 'unconsciousness', 'hair', 'mane', 'comma', 'eighth rest']],
  ['come', []],
  ['como', ['like', 'as']],
  ['con', []],
  ['copa', ['crop', 'crown', 'treetop', 'breakfast', 'cup']],
  ['copo', ['glass']],
  ['cor', ['color', 'colour']],
  ['crer', ['believe']],
  ['cria', ['young', 'offspring', 'kid', 'young\'un', 'ward', 'adoptee']],
  ['cruz', ['cross', 'dagger', 'lower back']],
  ['cu', ['buttock', 'arse', 'ass', 'butt', 'bum', 'anus']],
  ['cuba', ['cask', 'industrial', 'vat']],
  ['cuja', []],
  ['cujo', ['whose']],
  ['cura', ['cure', 'healing']],
  ['cá', ['here', 'hither']],
  ['cães', []],
  ['cão', ['dog']],
  ['céu', ['sky', 'heaven']],
  ['céus', ['good heavens']],
  ['d', []],
  ['da', ['of', 'from']],
  ['dada', []],
  ['dado', ['die', 'offered', 'granted', 'conceded', 'given', 'fixed']],
  ['dama', ['lady', 'queen', 'card game', 'board game', 'king']],
  ['dan', []],
  ['dano', ['damage', 'injury', 'video game', 'roleplaying game', 'danish', 'dane']],
  ['dar', ['to give']],
  ['dará', []],
  ['das', ['of', 'from']],
  ['data', ['date', 'large', 'quantity', 'lot', 'plot']],
  ['dava', []],
  ['davi', []],
  ['day', []],
  ['daí', ['then', 'afterwards', 'thus', 'sentence']],
  ['de', ['of', 'from']],
  ['dedo', ['digit', 'finger', 'dedo']],
  ['dei', []],
  ['del', []],
  ['dela', []],
  ['dele', []],
  ['der', []],
  ['des', []],
  ['deu', []],
  ['deus', ['god', 'deity']],
  ['deve', []],
  ['devo', []],
  ['dez', ['ten', 'awesome', 'amazing', 'cool', 'nice']],
  ['di', []],
  ['dia', ['day']],
  ['dias', []],
  ['dica', ['tip']],
  ['diga', []],
  ['digo', ['mean']],
  ['dita', ['positive', 'favorable', 'fate', 'destiny', 'prison', 'penitentiary']],
  ['dito', ['saying', 'proverb', 'said']],
  ['diz', []],
  ['dj', []],
  ['dna', []],
  ['do', ['of', 'from']],
  ['doce', ['sweet', 'sugary', 'water', 'fresh', 'figuratively', 'gentle']],
  ['dois', ['two']],
  ['dom', ['donation', 'gift', 'present', 'benefit', 'merit', 'advantage']],
  ['don', []],
  ['dona', ['proprietress', 'female', 'owner', 'housekeeper', 'governess', 'housewife']],
  ['dono', ['owner', 'patriarch', 'head', 'master']],
  ['dor', ['pain']],
  ['dos', ['of', 'from']],
  ['dose', ['dose', 'portion', 'fix']],
  ['dou', []],
  ['down', []],
  ['doze', ['twelve', 'shotgun']],
  ['dr', []],
  ['du', []],
  ['duas', []],
  ['duma', []],
  ['dura', []],
  ['duro', ['hard', 'unrelenting', 'unfriendly', 'severe', 'brutal', 'harsh']],
  ['dvd', []],
  ['dá', []],
  ['dão', []],
  ['dê', []],
  ['dói', []],
  ['e', ['and']],
  ['ed', []],
  ['eh', ['internet', 'text messaging', 'is', 'yeah']],
  ['ei', ['hey']],
  ['eis', ['here is', 'here are']],
  ['eixo', ['axle', 'axletree', 'axis']],
  ['el', ['the']],
  ['ela', ['she']],
  ['elas', ['they', 'female', 'them', 'it']],
  ['ele', ['he']],
  ['eles', ['they', 'them']],
  ['em', ['in', 'on']],
  ['emma', []],
  ['en', []],
  ['ep', []],
  ['era', ['era', 'age']],
  ['eram', []],
  ['eric', []],
  ['erro', ['error', 'mistake', 'difference']],
  ['es', []],
  ['essa', ['catafalque']],
  ['esse', ['that', 'this', 'that one', 'this one']],
  ['esta', ['this']],
  ['este', ['this']],
  ['está', ['is']],
  ['et', []],
  ['etc', []],
  ['eu', ['I']],
  ['eua', []],
  ['euro', ['euro']],
  ['eva', []],
  ['ex', ['ex']],
  ['f', []],
  ['faca', ['knife']],
  ['face', ['face']],
  ['fala', ['speech', 'spoken', 'phrase', 'line', 'accent', 'pronunciation']],
  ['fale', []],
  ['falo', ['phallus']],
  ['fama', ['fame', 'reputation']],
  ['fará', []],
  ['fase', ['phase', 'stage', 'period', 'video game', 'level']],
  ['fato', ['clothing', 'uniform', 'costume', 'suit', 'entrails', 'herd']],
  ['faz', []],
  ['fazê', []],
  ['faça', []],
  ['faço', []],
  ['fc', []],
  ['feio', ['ugly', 'immoral', 'disrespectful', 'impolite', 'rude', 'severely']],
  ['fez', ['faeces']],
  ['fi', ['phi', 'pronunciation spelling']],
  ['fica', []],
  ['fico', []],
  ['fiel', ['faithful', 'loyal', 'true', 'trustworthy', 'accurate', 'believer']],
  ['fifa', []],
  ['fila', ['queue']],
  ['fim', ['end']],
  ['fins', []],
  ['fio', ['thread', 'string', 'trickle', 'edge', 'chain', 'wire']],
  ['fita', ['tape', 'ribbon', 'band', 'film', 'movie', 'video game']],
  ['fiz', []],
  ['flor', ['flower']],
  ['foco', ['focus', 'source', 'transmission', 'disease', 'intent', 'headquarters']],
  ['foda', ['fuck', 'awesome', 'amazing', 'cool', 'bad', 'annoying']],
  ['fogo', ['fire']],
  ['foi', ['was']],
  ['fome', ['hunger', 'famine']],
  ['for', ['for loop']],
  ['fora', ['outside', 'abroad', 'overseas', 'out', 'away', 'except']],
  ['ford', []],
  ['foto', ['photo', 'photograph']],
  ['fox', []],
  ['fred', []],
  ['free', []],
  ['fria', []],
  ['frio', ['cold', 'cool', 'insensitive', 'coldness']],
  ['from', []],
  ['fuga', ['escape', 'flight', 'leak', 'evasion', 'music', 'fugue']],
  ['fui', []],
  ['fã', ['fan']],
  ['fãs', []],
  ['fé', ['faith']],
  ['g', []],
  ['gado', ['cattle', 'derogatory', 'minion', 'simp', 'manipulated', 'masses']],
  ['gajo', ['guy', 'bloke', 'dude']],
  ['gama', ['gamma', 'greek', 'beta', 'delta', 'series', 'chewing gum']],
  ['game', ['electronic game', 'computer game', 'video game']],
  ['gato', ['cat', 'domestic cat', 'feline', 'felid', 'iron', 'fix']],
  ['gay', ['gay', 'homosexual', 'flamboyant', 'effeminate', 'sentimental', 'derogatory']],
  ['gays', []],
  ['gelo', ['ice', 'coldness', 'cold', 'chill', 'white']],
  ['gera', []],
  ['get', []],
  ['gil', []],
  ['gira', ['spirit', 'medium', 'umbanda']],
  ['girl', []],
  ['giro', ['rotation', 'turn', 'pretty', 'beautiful', 'interesting', 'nice']],
  ['go', ['board game', 'go']],
  ['gol', ['goal']],
  ['gols', []],
  ['good', []],
  ['got', []],
  ['grau', ['degree', 'wheelie']],
  ['guia', ['guide', 'leash']],
  ['gás', ['gas']],
  ['h', ['internet', 'bahia']],
  ['ha', []],
  ['haja', []],
  ['hd', []],
  ['hein', ['huh', 'hm', 'eh', 'tag question']],
  ['hill', []],
  ['hino', ['hymn', 'anthem', 'bop']],
  ['hip', []],
  ['hit', ['hit']],
  ['hoje', ['today', 'nowadays']],
  ['home', []],
  ['hong', []],
  ['hora', ['hour', 'time']],
  ['how', []],
  ['http', []],
  ['hugo', []],
  ['há', ['there is']],
  ['i', []],
  ['i\'m', []],
  ['ia', []],
  ['iam', []],
  ['ian', []],
  ['ida', ['going', 'departure', 'trip']],
  ['ido', ['ido']],
  ['if', []],
  ['ii', []],
  ['iii', []],
  ['il', []],
  ['ilha', ['island']],
  ['in', ['in fashion']],
  ['indo', []],
  ['ir', ['to go']],
  ['ira', ['anger', 'rage']],
  ['irei', []],
  ['iria', []],
  ['irmã', ['sister']],
  ['irá', ['meliponine']],
  ['irã', []],
  ['irão', []],
  ['is', []],
  ['isso', ['that']],
  ['isto', ['this']],
  ['it', []],
  ['iv', []],
  ['ivan', []],
  ['j', []],
  ['ja', []],
  ['jack', ['jack', 'jack plug', 'rapist', 'internet', 'pedophile']],
  ['jane', []],
  ['jato', ['jet', 'hurling', 'throwing', 'throw', 'flash', 'flow']],
  ['jay', []],
  ['jean', []],
  ['jim', []],
  ['joe', []],
  ['joga', []],
  ['jogo', ['game']],
  ['john', []],
  ['josé', []],
  ['joão', ['nobody', 'dribbled']],
  ['jr', []],
  ['juan', []],
  ['juiz', ['judge', 'referee', 'umpire']],
  ['juro', ['interest', 'bonus', 'reward', 'usury']],
  ['just', []],
  ['já', ['already']],
  ['júri', ['law', 'jury']],
  ['k', []],
  ['kg', []],
  ['kim', []],
  ['king', []],
  ['kit', ['kit']],
  ['km', []],
  ['kong', []],
  ['l', ['stereotypical', 'chinese']],
  ['la', ['mesoclitic', 'consonant']],
  ['lado', ['side']],
  ['lady', []],
  ['lago', ['lake']],
  ['lama', ['mud', 'lama']],
  ['lar', ['endearing', 'home', 'hearth', 'oven']],
  ['las', ['mesoclitic', 'consonant']],
  ['last', []],
  ['lava', ['lava']],
  ['le', []],
  ['lee', []],
  ['lei', ['law']],
  ['leia', []],
  ['leis', []],
  ['leo', []],
  ['ler', ['to read']],
  ['les', []],
  ['leu', ['leu']],
  ['leva', ['wave']],
  ['leve', ['light', 'gentle']],
  ['levo', []],
  ['leão', ['lion']],
  ['lgbt', []],
  ['lhe', ['him', 'her']],
  ['lhes', []],
  ['li', []],
  ['lido', ['well-read']],
  ['life', []],
  ['liga', ['alloy', 'league', 'group', 'association', 'connection', 'garter']],
  ['ligo', []],
  ['like', ['social media', 'like']],
  ['lima', ['lime', 'file']],
  ['line', []],
  ['link', ['link']],
  ['lisa', []],
  ['live', ['video stream', 'live stream']],
  ['lixo', ['garbage', 'waste', 'rubbish', 'rubbish bin', 'trash can', 'crap']],
  ['lo', ['mesoclitic', 'consonant']],
  ['lobo', ['wolf', 'lobe']],
  ['logo', ['soon', 'immediately', 'right', 'already', 'thus', 'therefore']],
  ['loja', ['shop', 'store', 'basement', 'cellar', 'lodge']],
  ['long', []],
  ['look', ['look', 'outfit', 'style']],
  ['los', ['mesoclitic', 'consonant']],
  ['love', []],
  ['lua', ['moonlight', 'moonshine', 'moon']],
  ['luis', []],
  ['luiz', []],
  ['lula', ['squid']],
  ['luta', ['fight', 'striving']],
  ['luto', ['mourning']],
  ['luxo', ['extravagance', 'prodigality', 'luxury']],
  ['luz', ['light']],
  ['luís', ['louis']],
  ['lá', ['there']],
  ['lê', []],
  ['m', []],
  ['ma', []],
  ['mac', []],
  ['maia', ['maya', 'yucatec maya', 'mayan']],
  ['mail', []],
  ['maio', ['may']],
  ['mais', ['more']],
  ['make', ['makeup']],
  ['mal', ['bad']],
  ['mala', ['suitcase', 'luggage', 'boot', 'trunk', 'handbag', 'irritating']],
  ['mama', ['breast', 'bosom', 'udder', 'teat']],
  ['man', []],
  ['mano', ['brother', 'sibling', 'bro', 'homie', 'dude', 'man']],
  ['mapa', ['map', 'board game', 'video game']],
  ['mar', ['sea']],
  ['mark', []],
  ['mary', []],
  ['mas', ['but']],
  ['mata', ['woods', 'forest', 'dodgeball']],
  ['mato', ['forest', 'bush', 'jungle', 'woods', 'grass', 'weed']],
  ['matt', []],
  ['mau', ['bad']],
  ['maus', []],
  ['max', []],
  ['may', []],
  ['me', ['me']],
  ['medo', ['fear', 'median']],
  ['mega', ['very', 'super']],
  ['meia', ['pint', 'sock', 'half past', 'six', 'midfielder']],
  ['meio', ['half', 'middle']],
  ['mel', ['honey', 'molasses']],
  ['melo', []],
  ['mesa', ['table']],
  ['meta', ['goal', 'target', 'video game', 'meta']],
  ['meu', ['my', 'mine', 'hey', 'oi', 'whoa', 'dude']],
  ['meus', ['kin', 'folk', 'fellow', 'kind', 'friend', 'subordinate']],
  ['mexe', []],
  ['mg', []],
  ['mi', ['mi', 'mu']],
  ['mike', []],
  ['mil', ['thousand', 'thousands']],
  ['mim', ['prepositional pronoun', 'subordinate clause']],
  ['min', ['min']],
  ['mina', ['mine', 'fount', 'girl', 'gal']],
  ['mini', []],
  ['miss', []],
  ['mito', ['myth', 'legend']],
  ['mix', []],
  ['mm', ['internet', 'text messaging']],
  ['mo', []],
  ['moda', ['fashion', 'way', 'manner', 'ballad', 'mode']],
  ['modo', ['way', 'mode']],
  ['mora', ['delay', 'payment', 'debt', 'mulct', 'in time', 'mora']],
  ['more', []],
  ['moro', []],
  ['moto', ['motorcycle', 'movement', 'motion', 'agitation', 'circulation', 'rotation']],
  ['moça', ['girl', 'young lady']],
  ['mr', []],
  ['ms', []],
  ['mt', ['internet', 'text messaging']],
  ['muda', ['seedling', 'ecdysis', 'moult']],
  ['mude', []],
  ['mudo', ['mute', 'muteness', 'utter', 'silent']],
  ['muro', ['wall']],
  ['my', []],
  ['má', []],
  ['más', []],
  ['mãe', ['mother']],
  ['mães', []],
  ['mão', ['hand']],
  ['mãos', []],
  ['mês', ['month']],
  ['n', ['internet', 'text messaging']],
  ['na', ['in the', 'on the']],
  ['nada', ['nothing']],
  ['nao', []],
  ['nas', ['nasal']],
  ['nave', ['ship', 'nave', 'aisle', 'car', 'science fiction']],
  ['nd', ['internet', 'text messaging']],
  ['nega', ['refusal', 'fail', 'endearing', 'regional', 'woman']],
  ['nela', []],
  ['nele', ['paddy']],
  ['nem', ['not even', 'do', 'not', 'even', 'neither', 'nor']],
  ['net', ['net', 'internet']],
  ['neto', ['grandson', 'grandchild']],
  ['neve', ['snow']],
  ['new', []],
  ['news', []],
  ['nick', ['internet', 'video game', 'nick', 'nickname']],
  ['nina', []],
  ['no', ['in the', 'on the']],
  ['nome', ['name']],
  ['nos', ['us']],
  ['not', []],
  ['nota', ['banknote', 'mark', 'grade']],
  ['note', []],
  ['nova', ['news', 'nova']],
  ['nove', ['nine']],
  ['novo', ['new']],
  ['now', []],
  ['nu', ['naked', 'nude']],
  ['num', []],
  ['numa', []],
  ['nuno', []],
  ['nº', []],
  ['não', ['no', 'not']],
  ['né', ['tag question', 'innit', 'right', 'duh', 'obviously']],
  ['nós', ['we']],
  ['o', ['the']],
  ['obra', ['construction', 'construction site', 'work']],
  ['of', []],
  ['off', []],
  ['oh', []],
  ['oi', ['hey', 'sorry', 'i beg your pardon', 'excuse me']],
  ['oito', ['cardinal number', 'eight', 'eighth', 'card game']],
  ['ok', []],
  ['old', []],
  ['olha', ['stew', 'meat', 'chickpea', 'pea', 'vegetable', 'earthenware']],
  ['olhe', []],
  ['olho', ['eye']],
  ['olá', ['hello', 'hi']],
  ['on', []],
  ['onda', ['wave', 'undulation', 'fashion']],
  ['onde', ['where']],
  ['one', []],
  ['onu', []],
  ['onze', ['eleven']],
  ['open', []],
  ['or', []],
  ['ora', ['now', 'sometimes', 'duh', 'obviously', 'oh no']],
  ['oral', ['oral', 'exam', 'oral sex', 'blowjob']],
  ['os', ['the']],
  ['osso', ['bone', 'difficulty', 'difficult', 'annoying']],
  ['ou', ['or', 'either', 'inclusive or']],
  ['ouro', ['gold']],
  ['out', []],
  ['ouve', []],
  ['ouvi', []],
  ['ouça', []],
  ['ouço', []],
  ['ovo', ['egg', 'body', 'chicken', 'fertilized', 'intended', 'food']],
  ['ovos', []],
  ['p', ['internet', 'text messaging']],
  ['pa', []],
  ['paga', ['payback']],
  ['pago', ['paid']],
  ['pai', ['father']],
  ['pais', ['parents']],
  ['pan', []],
  ['pano', ['cloth', 'rag', 'tatter']],
  ['papa', ['pope', 'pap', 'baby food', 'childish', 'food', 'pasty']],
  ['papo', ['crop', 'stomach', 'goitre', 'chat']],
  ['par', ['pair', 'partner', 'couple', 'peer', 'par', 'even']],
  ['para', ['for', 'to']],
  ['pare', []],
  ['park', []],
  ['part', []],
  ['pará', []],
  ['pau', ['stick', 'wood', 'penis', 'dick', 'cock', 'prick']],
  ['paul', ['swamp']],
  ['paz', ['peace']],
  ['país', ['country']],
  ['pc', []],
  ['pdf', []],
  ['pe', []],
  ['pede', []],
  ['pedi', []],
  ['pega', ['magpie', 'prating', 'gossiper', 'whore', 'slut', 'handle']],
  ['pego', ['bottom', 'sea', 'deepest', 'point', 'body of water', 'underwater']],
  ['pela', []],
  ['pele', ['skin', 'fur']],
  ['pelo', ['hair', 'fur', 'filament']],
  ['pena', ['punishment', 'pain', 'sadness', 'pity', 'what a shame', 'what a pity']],
  ['per', []],
  ['peru', ['wild turkey', 'turkey', 'penis']],
  ['peso', ['weight', 'heaviness', 'shot', 'weight class', 'boldness', 'peso']],
  ['peça', ['piece', 'play', 'room', 'gun', 'cock', 'dick']],
  ['peço', []],
  ['pib', []],
  ['pior', []],
  ['piso', ['storey', 'floor', 'surface']],
  ['play', []],
  ['plus', []],
  ['pm', []],
  ['pmdb', []],
  ['pode', []],
  ['pois', ['so', 'then', 'because', 'for']],
  ['pop', ['pop']],
  ['por', ['for', 'by']],
  ['post', ['internet', 'post']],
  ['povo', ['people']],
  ['poço', ['well', 'pit']],
  ['pp', []],
  ['pq', ['why', 'by', 'what', 'internet', 'text messaging', 'reason']],
  ['pr', []],
  ['pra', []],
  ['pro', []],
  ['prof', []],
  ['pré', []],
  ['pró', ['pro', 'in favour of']],
  ['psdb', []],
  ['pt', []],
  ['pude', []],
  ['pura', []],
  ['puro', ['pure', 'flawless', 'clean', 'sober']],
  ['puta', ['derogatory', 'slutty', 'intensifier', 'fucking', 'whore', 'hooker']],
  ['puxa', []],
  ['pá', ['shovel', 'spade', 'windmill', 'blade', 'paddle', 'oar']],
  ['pão', ['bread']],
  ['pé', ['foot']],
  ['pés', []],
  ['pó', ['powder', 'dust', 'cocaine']],
  ['pós', []],
  ['pôde', []],
  ['pôr', ['to put']],
  ['põe', []],
  ['q', ['internet', 'text messaging', 'what']],
  ['qual', ['which']],
  ['que', ['that', 'what']],
  ['quem', ['who']],
  ['quer', ['whether', 'or']],
  ['quis', []],
  ['quão', ['how', 'as']],
  ['quê', ['what', 'characteristic']],
  ['r', []],
  ['rabo', ['tail', 'butt', 'buttocks']],
  ['raio', ['ray', 'beam', 'lightning', 'radius', 'spoke']],
  ['raiz', ['root', 'graph theory', 'true', 'traditional']],
  ['ramo', ['bouquet', 'bunch', 'bough', 'branch', 'subject', 'field']],
  ['rap', ['rap music']],
  ['raro', ['rare', 'exceptional', 'extraordinary', 'sparse', 'rarely']],
  ['rato', ['rat', 'mouse', 'computer', 'hardware', 'burglar', 'thief']],
  ['raul', ['swindler', 'embezzler']],
  ['ray', []],
  ['raça', ['race', 'breed', 'brood']],
  ['re', []],
  ['real', ['true', 'real', 'physical', 'set', 'real number', 'truth']],
  ['red', []],
  ['rede', ['net', 'hairnet', 'sieve', 'web', 'trap', 'hammock']],
  ['rei', ['king', 'chess', 'card game']],
  ['reis', []],
  ['reta', ['line', 'straight', 'path', 'road']],
  ['rica', []],
  ['rick', []],
  ['rico', ['rich', 'wealthy', 'luxurious', 'tasty', 'cute']],
  ['rio', ['river']],
  ['rios', []],
  ['rir', ['laugh', 'make fun of']],
  ['rita', []],
  ['rj', []],
  ['rock', ['rock']],
  ['roda', ['wheel', 'cartwheel', 'foundling wheel', 'circle']],
  ['roma', ['roma']],
  ['rosa', ['rose', 'blush', 'beautiful', 'ceiling', 'medallion', 'brass']],
  ['rose', []],
  ['rota', ['route', 'combat', 'defeat', 'rota', 'roman catholicism', 'rattan']],
  ['rs', ['internet', 'text messaging', 'lol', 'haha']],
  ['rua', ['street']],
  ['ruas', []],
  ['rui', []],
  ['ruim', ['bad', 'unpleasant', 'evil']],
  ['rumo', ['course', 'path', 'heading', 'bearing']],
  ['ryan', []],
  ['s', ['internet', 'text messaging']],
  ['sa', []],
  ['sabe', []],
  ['saco', ['bag', 'sack', 'balls', 'nuts', 'patience', 'tolerance']],
  ['saem', []],
  ['sai', []],
  ['saia', ['skirt']],
  ['sair', ['to leave', 'to go out']],
  ['saiu', []],
  ['sal', ['salt', 'bath salt', 'wit', 'engaging', 'sal']],
  ['sala', ['room', 'class']],
  ['sam', []],
  ['san', []],
  ['sao', []],
  ['sara', []],
  ['saí', ['buddhist', 'monk', 'bonze']],
  ['sbt', []],
  ['sc', []],
  ['se', ['if', 'oneself']],
  ['seca', ['drought', 'drying', 'nuisance', 'bore']],
  ['seco', ['devoid', 'liquid', 'dry', 'desiccated', 'withered', 'insensible']],
  ['sede', ['thirst', 'craving', 'headquarters', 'seat', 'see', 'diocese']],
  ['sei', ['sarcastic']],
  ['seis', ['six']],
  ['seja', []],
  ['selo', ['seal', 'stamp']],
  ['sem', ['without']],
  ['semi', []],
  ['ser', ['to be']],
  ['será', []],
  ['set', ['set']],
  ['sete', ['seven', 'card game']],
  ['seu', ['his', 'her', 'its', 'their', 'your', 'you']],
  ['seus', ['kin', 'folk', 'fellow', 'kind', 'friend', 'subordinate']],
  ['sexo', ['sex', 'gender', 'sexual intercourse', 'sex organ', 'genitalia']],
  ['sexy', ['sexy']],
  ['show', ['show', 'concert', 'spectacle', 'display', 'feat', 'cry']],
  ['si', ['oneself', 'yourself', 'himself', 'herself', 'itself', 'yourselves']],
  ['sido', []],
  ['siga', []],
  ['sim', ['yes']],
  ['sir', ['sir']],
  ['site', ['site', 'web site']],
  ['sms', []],
  ['so', []],
  ['sob', ['under']],
  ['sobe', []],
  ['sofá', ['sofa']],
  ['sol', ['sun']],
  ['solo', ['soil', 'ground', 'music', 'solo']],
  ['som', ['sound']],
  ['soma', ['sum', 'soma']],
  ['some', []],
  ['sono', ['sleep', 'sleepiness']],
  ['sons', []],
  ['sopa', ['soup', 'stock']],
  ['sou', []],
  ['sp', []],
  ['sr', []],
  ['st', []],
  ['star', []],
  ['stf', []],
  ['sua', []],
  ['suas', []],
  ['sub', []],
  ['suco', ['juice', 'liquid', 'gland']],
  ['suja', []],
  ['sujo', ['dirt', 'grime', 'dirty', 'unclean', 'offensive', 'standard']],
  ['sul', ['south']],
  ['são', ['are']],
  ['só', ['only']],
  ['t', []],
  ['ta', []],
  ['tag', ['tag', 'rfid chip']],
  ['tais', ['tais', 'east timor']],
  ['tal', ['such', 'one', 'such-and-such']],
  ['tava', []],
  ['taxa', ['fee', 'tax', 'rate', 'percentage', 'ratio']],
  ['taça', ['cup', 'tazza', 'goblet', 'bowl', 'trophy']],
  ['te', ['you']],
  ['team', []],
  ['tela', ['canvas', 'painting', 'screen', 'cinema', 'tissue']],
  ['tem', ['has']],
  ['tema', ['theme', 'topic', 'subject', 'motif', 'music', 'linguistic']],
  ['tens', []],
  ['ter', ['to have']],
  ['terá', []],
  ['tese', ['thesis']],
  ['teto', ['ceiling', 'tit']],
  ['teu', ['your', 'thine', 'thy', 'yours', 'religious', 'hey']],
  ['teus', ['religious', 'thy', 'kin', 'folk', 'fellow', 'kind']],
  ['teve', []],
  ['that', []],
  ['the', []],
  ['this', []],
  ['ti', []],
  ['tia', ['aunt']],
  ['tido', []],
  ['tim', ['berimbau']],
  ['time', ['team', 'sexual orientation']],
  ['tio', ['uncle', 'guy', 'bloke', 'bro', 'posh', 'snobby']],
  ['tipo', ['kind', 'sort', 'type', 'typology', 'guy', 'bloke']],
  ['tira', ['strip', 'comic', 'law enforcement', 'cop', 'police officer']],
  ['tiro', ['shoot', 'fire', 'shot', 'shooting', 'firearm', 'sport']],
  ['tive', []],
  ['to', []],
  ['toca', ['den', 'burrow', 'refuge', 'hiding place', 'bedroom', 'root']],
  ['toda', ['all', 'every']],
  ['todo', ['all', 'every']],
  ['tom', ['tone']],
  ['toma', []],
  ['tome', []],
  ['tomé', []],
  ['tony', []],
  ['top', ['cool', 'awesome', 'top', 'excellent', 'high-quality']],
  ['topo', ['top', 'apex', 'collision']],
  ['tour', ['tour']],
  ['traz', []],
  ['trem', ['set', 'train', 'rail transport', 'thingy', 'thingummy', 'bus']],
  ['trio', ['trio']],
  ['trás', ['behind', 'rear']],
  ['três', ['three']],
  ['tu', ['you']],
  ['tua', []],
  ['tuas', []],
  ['tudo', ['everything']],
  ['tv', []],
  ['two', []],
  ['tá', ['ok', 'all right']],
  ['tão', ['so', 'as']],
  ['têm', []],
  ['tô', []],
  ['u', ['where']],
  ['ue', []],
  ['um', ['a', 'one']],
  ['uma', ['a', 'one']],
  ['umas', []],
  ['un', []],
  ['une', []],
  ['unir', ['bind', 'connect', 'unite']],
  ['uns', ['about', 'some']],
  ['up', []],
  ['us', []],
  ['usa', []],
  ['usam', []],
  ['usar', ['to use']],
  ['use', []],
  ['usei', []],
  ['uso', ['use', 'usage', 'habit', 'wear']],
  ['usou', []],
  ['usp', []],
  ['usá', []],
  ['v', []],
  ['vaca', ['cow', 'beef', 'sexist', 'promiscuous', 'bitch']],
  ['vaga', ['wave', 'vacancy', 'opening', 'parking space', 'slot', 'spot']],
  ['vai', []],
  ['vais', []],
  ['vale', ['valley', 'voucher', 'coupon']],
  ['van', ['van']],
  ['vc', ['internet', 'text messaging']],
  ['veio', ['vein', 'rivulet']],
  ['veja', ['mediterranean', 'parrotfish', 'sparisoma cretense']],
  ['vejo', []],
  ['vela', ['candle', 'third wheel', 'sail', 'sailing']],
  ['vem', []],
  ['ver', ['to see']],
  ['vez', ['time', 'turn']],
  ['vi', []],
  ['via', ['way', 'path', 'rail transport', 'gauge', 'medium', 'example']],
  ['vias', []],
  ['vice', []],
  ['vida', ['life']],
  ['vila', ['town', 'country house', 'row houses', 'cul-de-sac', 'slum']],
  ['vim', []],
  ['vir', ['to come']],
  ['vira', []],
  ['visa', []],
  ['viu', []],
  ['viva', ['hooray', 'long live', 'three cheers', 'hello', 'hi', 'bless you']],
  ['vive', []],
  ['vivo', ['alive', 'lively', 'vivacious', 'native', 'strong']],
  ['voar', ['fly']],
  ['voce', []],
  ['você', ['you']],
  ['voo', ['flight']],
  ['vos', []],
  ['voto', ['vote', 'vow', 'offering']],
  ['vou', []],
  ['voz', ['voice']],
  ['vs', []],
  ['vá', []],
  ['vão', ['vain', 'pretentious', 'overambitious', 'pointless', 'futile', 'useless']],
  ['vê', []],
  ['vêem', []],
  ['vêm', []],
  ['vós', ['humorous', 'you', 'ye', 'thou']],
  ['w', []],
  ['war', []],
  ['way', []],
  ['we', []],
  ['web', ['world wide web']],
  ['west', []],
  ['what', []],
  ['who', []],
  ['will', []],
  ['with', []],
  ['x', ['internet', 'text messaging']],
  ['xix', []],
  ['xx', []],
  ['y', []],
  ['ya', []],
  ['york', []],
  ['you', []],
  ['your', []],
  ['z', []],
  ['zero', ['zero', 'nothing']],
  ['zona', ['zone', 'area', 'region', 'mess', 'red light district', 'brothel']],
  ['zé', ['derogatory', 'joe', 'pleb', 'social class']],
  ['º', []],
  ['à', ['a', 'in']],
  ['às', []],
  ['á', ['wing']],
  ['água', ['water']],
  ['área', ['area', 'region', 'place', 'field', 'penalty area', 'court']],
  ['ás', ['card game', 'ace']],
  ['ásia', []],
  ['é', ['is']],
  ['és', []],
  ['ó', ['o', 'hey', 'look']],
  ['ódio', ['hatred']],
  ['óleo', ['oil', 'olive oil', 'based', 'paint', 'oil painting', 'essential oil']],
  ['útil', ['profitable', 'advantageous', 'helpful', 'useful', 'valid']],
]);
