// Curated English glosses for Spanish lemmas of four characters or fewer.
//
// These high-frequency short words are where the Wiktionary-derived pipeline is
// weakest: raw sense links drag in stray letters, abbreviations, proper nouns,
// English code-switches and conjugated forms. For every lemma here this map is
// authoritative and fully replaces the Wiktionary glosses. An empty list drops
// the lemma from the deck, which is how letters and abbreviations are removed.
//
// Generated from a curated table; regenerate the deck after editing.

export const SPANISH_SHORT_WORD_MAX_LENGTH = 4;

export const SPANISH_SHORT_WORD_GLOSSES: ReadonlyMap<string, readonly string[]> = new Map<
  string,
  readonly string[]
>([
  ['a', ['to', 'at']],
  ['e', ['and']],
  ['o', ['or']],
  ['u', ['or']],
  ['y', ['and']],
  ['ah', ['ah']],
  ['al', ['to the', 'at the']],
  ['ay', ['ouch', 'alas']],
  ['de', ['of', 'from']],
  ['eh', ['hey']],
  ['el', ['the']],
  ['en', ['in', 'on']],
  ['fe', ['faith']],
  ['ir', ['to go']],
  ['la', ['the']],
  ['le', ['him', 'her']],
  ['lo', ['it', 'the']],
  ['mi', ['my']],
  ['mí', ['me']],
  ['ni', ['nor']],
  ['no', ['no', 'not']],
  ['oh', ['oh']],
  ['os', ['you']],
  ['se', ['oneself']],
  ['si', ['if']],
  ['su', ['his', 'her', 'their']],
  ['sé', ['i know']],
  ['sí', ['yes']],
  ['te', ['you']],
  ['tu', ['your']],
  ['té', ['tea']],
  ['tí', ['you']],
  ['tú', ['you']],
  ['un', ['a', 'one']],
  ['ya', ['already', 'now']],
  ['yo', ['i']],
  ['él', ['he']],
  ['acá', ['here']],
  ['ahí', ['there']],
  ['ala', ['wing']],
  ['ama', ['housekeeper', 'landlady']],
  ['amo', ['master', 'owner']],
  ['así', ['like this', 'so']],
  ['aun', ['even']],
  ['año', ['year']],
  ['aún', ['still', 'yet']],
  ['bar', ['bar']],
  ['bus', ['bus']],
  ['con', ['with']],
  ['dar', ['to give']],
  ['del', ['of the', 'from the']],
  ['dos', ['two']],
  ['día', ['day']],
  ['eco', ['echo']],
  ['eje', ['axis']],
  ['ese', ['that']],
  ['fan', ['fan']],
  ['feo', ['ugly']],
  ['fin', ['end']],
  ['gas', ['gas']],
  ['gay', ['gay']],
  ['gol', ['goal']],
  ['hay', ['there is', 'there are']],
  ['hoy', ['today']],
  ['ida', ['departure', 'going']],
  ['ira', ['anger']],
  ['las', ['the']],
  ['les', ['them']],
  ['ley', ['law']],
  ['luz', ['light']],
  ['mal', ['bad', 'evil']],
  ['mar', ['sea']],
  ['mas', ['but']],
  ['mes', ['month']],
  ['mil', ['thousand']],
  ['muy', ['very']],
  ['más', ['more']],
  ['mía', ['mine']],
  ['mío', ['mine']],
  ['nos', ['us']],
  ['ojo', ['eye']],
  ['ola', ['wave']],
  ['oro', ['gold']],
  ['oír', ['to hear']],
  ['pan', ['bread']],
  ['par', ['pair']],
  ['paz', ['peace']],
  ['pez', ['fish']],
  ['pie', ['foot']],
  ['por', ['for', 'by']],
  ['pro', ['pro', 'advantage']],
  ['que', ['that', 'than']],
  ['qué', ['what']],
  ['red', ['net', 'network']],
  ['rey', ['king']],
  ['rol', ['role']],
  ['río', ['river']],
  ['sal', ['salt']],
  ['ser', ['to be']],
  ['sin', ['without']],
  ['sol', ['sun']],
  ['sur', ['south']],
  ['sus', ['his', 'her', 'their']],
  ['tal', ['such']],
  ['tan', ['so', 'such']],
  ['tía', ['aunt']],
  ['tío', ['uncle']],
  ['una', ['a', 'one']],
  ['uno', ['one']],
  ['uso', ['use']],
  ['ver', ['to see']],
  ['vez', ['time', 'instance']],
  ['vos', ['you']],
  ['voz', ['voice']],
  ['vía', ['way', 'road']],
  ['acta', ['minutes', 'record']],
  ['acto', ['act']],
  ['agua', ['water']],
  ['aire', ['air']],
  ['alba', ['dawn']],
  ['algo', ['something']],
  ['allá', ['there', 'over there']],
  ['allí', ['there']],
  ['alma', ['soul']],
  ['alto', ['tall', 'high', 'loud']],
  ['amar', ['to love']],
  ['amor', ['love']],
  ['ante', ['in front of', 'before']],
  ['aquí', ['here']],
  ['arco', ['bow', 'arc']],
  ['arma', ['weapon']],
  ['arte', ['art']],
  ['asco', ['disgust']],
  ['auto', ['car']],
  ['ayer', ['yesterday']],
  ['azar', ['chance', 'random']],
  ['azul', ['blue']],
  ['bajo', ['low', 'short']],
  ['base', ['base', 'basis']],
  ['baño', ['bathroom', 'bath']],
  ['bebé', ['baby']],
  ['beso', ['kiss']],
  ['bien', ['well', 'good']],
  ['blog', ['blog']],
  ['boca', ['mouth']],
  ['boda', ['wedding']],
  ['bola', ['ball']],
  ['cabo', ['end', 'cape']],
  ['cada', ['each', 'every']],
  ['caer', ['to fall']],
  ['café', ['coffee']],
  ['caja', ['box', 'case']],
  ['cama', ['bed']],
  ['caos', ['chaos']],
  ['capa', ['layer', 'cape']],
  ['cara', ['face']],
  ['caro', ['expensive', 'dear']],
  ['casa', ['house']],
  ['casi', ['almost']],
  ['caso', ['case']],
  ['caza', ['hunting']],
  ['cena', ['dinner']],
  ['cero', ['zero']],
  ['cien', ['one hundred']],
  ['cine', ['cinema']],
  ['cita', ['appointment', 'date']],
  ['club', ['club']],
  ['cola', ['tail', 'queue']],
  ['como', ['like', 'as']],
  ['copa', ['glass', 'cup']],
  ['coro', ['choir', 'chorus']],
  ['cosa', ['thing']],
  ['cruz', ['cross']],
  ['cual', ['which']],
  ['cura', ['priest', 'cure']],
  ['cuyo', ['whose']],
  ['cuál', ['which', 'what']],
  ['cómo', ['how']],
  ['dado', ['given']],
  ['dama', ['lady']],
  ['dato', ['fact', 'piece of data']],
  ['daño', ['damage', 'harm']],
  ['dedo', ['finger']],
  ['diez', ['ten']],
  ['dios', ['god']],
  ['doce', ['twelve']],
  ['duda', ['doubt']],
  ['duro', ['hard', 'tough']],
  ['edad', ['age']],
  ['ella', ['she']],
  ['ello', ['it']],
  ['esas', ['those']],
  ['esos', ['those']],
  ['este', ['this']],
  ['fama', ['fame']],
  ['fase', ['phase']],
  ['fiel', ['faithful', 'loyal']],
  ['fijo', ['fixed', 'firm']],
  ['fila', ['row', 'line']],
  ['flor', ['flower']],
  ['foro', ['forum']],
  ['foto', ['photo']],
  ['frío', ['cold']],
  ['fuga', ['escape', 'leak']],
  ['gama', ['range']],
  ['gana', ['desire', 'urge']],
  ['gato', ['cat']],
  ['gira', ['tour']],
  ['giro', ['turn', 'transfer']],
  ['gris', ['grey']],
  ['guía', ['guide']],
  ['hija', ['daughter']],
  ['hijo', ['son']],
  ['hilo', ['thread']],
  ['hoja', ['leaf', 'sheet']],
  ['hola', ['hello']],
  ['hora', ['hour', 'time']],
  ['huir', ['to flee']],
  ['humo', ['smoke']],
  ['idea', ['idea']],
  ['isla', ['island']],
  ['jefe', ['boss', 'chief']],
  ['juez', ['judge']],
  ['lado', ['side']],
  ['lago', ['lake']],
  ['lana', ['wool']],
  ['leer', ['to read']],
  ['león', ['lion']],
  ['liga', ['league']],
  ['lima', ['lime', 'file']],
  ['lobo', ['wolf']],
  ['loco', ['crazy']],
  ['lujo', ['luxury']],
  ['luna', ['moon']],
  ['malo', ['bad']],
  ['mama', ['mom']],
  ['mamá', ['mom', 'mother']],
  ['mano', ['hand']],
  ['mapa', ['map']],
  ['masa', ['dough', 'mass']],
  ['maya', ['mayan']],
  ['mayo', ['may']],
  ['maíz', ['corn']],
  ['mesa', ['table']],
  ['meta', ['goal']],
  ['miel', ['honey']],
  ['mina', ['mine']],
  ['misa', ['mass']],
  ['mito', ['myth']],
  ['moda', ['fashion']],
  ['modo', ['way', 'manner']],
  ['moto', ['motorcycle']],
  ['muro', ['wall']],
  ['nada', ['nothing']],
  ['nave', ['ship']],
  ['niña', ['girl']],
  ['niño', ['child', 'boy']],
  ['nota', ['note']],
  ['obra', ['work']],
  ['ocho', ['eight']],
  ['odio', ['hatred']],
  ['olor', ['smell']],
  ['once', ['eleven']],
  ['onda', ['wave']],
  ['oral', ['oral']],
  ['otro', ['other']],
  ['oído', ['hearing', 'ear']],
  ['paga', ['payment', 'pay']],
  ['pago', ['payment']],
  ['palo', ['stick']],
  ['papa', ['potato', 'pope']],
  ['papá', ['dad']],
  ['para', ['for', 'in order to']],
  ['paro', ['strike', 'stoppage']],
  ['pasa', ['raisin']],
  ['pase', ['pass', 'permit']],
  ['paso', ['step']],
  ['país', ['country']],
  ['pelo', ['hair']],
  ['pena', ['pity', 'punishment']],
  ['pero', ['but']],
  ['peso', ['weight']],
  ['peña', ['rock', 'group of friends']],
  ['pico', ['beak', 'peak']],
  ['piel', ['skin']],
  ['piso', ['floor', 'apartment']],
  ['plan', ['plan']],
  ['poco', ['little', 'few']],
  ['pozo', ['well']],
  ['pues', ['so', 'then']],
  ['puro', ['pure']],
  ['rama', ['branch']],
  ['raro', ['strange', 'rare']],
  ['rato', ['while']],
  ['rayo', ['ray', 'lightning bolt']],
  ['raza', ['race', 'breed']],
  ['raíz', ['root']],
  ['real', ['real', 'royal']],
  ['reto', ['challenge']],
  ['rico', ['rich', 'tasty']],
  ['risa', ['laughter']],
  ['robo', ['robbery']],
  ['roca', ['rock']],
  ['rojo', ['red']],
  ['ropa', ['clothes']],
  ['rosa', ['rose', 'pink']],
  ['roto', ['broken']],
  ['ruta', ['route']],
  ['saco', ['bag', 'sack']],
  ['sala', ['room', 'hall']],
  ['sano', ['healthy']],
  ['seco', ['dry']],
  ['sede', ['seat', 'headquarters']],
  ['seis', ['six']],
  ['sexo', ['sex']],
  ['sino', ['but', 'fate']],
  ['solo', ['alone', 'only']],
  ['suma', ['sum']],
  ['suyo', ['his', 'hers']],
  ['sólo', ['only']],
  ['tasa', ['rate']],
  ['taxi', ['taxi']],
  ['tela', ['fabric', 'cloth']],
  ['tele', ['tv']],
  ['tema', ['topic', 'theme']],
  ['test', ['test']],
  ['tipo', ['type', 'kind']],
  ['tiro', ['shot', 'throw']],
  ['todo', ['all', 'everything']],
  ['tomo', ['volume', 'tome']],
  ['tono', ['tone']],
  ['toro', ['bull']],
  ['tras', ['after', 'behind']],
  ['tren', ['train']],
  ['tres', ['three']],
  ['tubo', ['tube', 'pipe']],
  ['tuyo', ['yours']],
  ['unos', ['some']],
  ['usar', ['to use']],
  ['vaca', ['cow']],
  ['vale', ['ok', 'voucher']],
  ['vaso', ['glass']],
  ['vega', ['meadow']],
  ['vela', ['candle', 'sail']],
  ['vida', ['life']],
  ['vino', ['wine']],
  ['vivo', ['alive', 'living']],
  ['voto', ['vote']],
  ['zona', ['zone', 'area']],
  ['área', ['area']],
  ['éste', ['this one']],
  ['útil', ['useful']],
  // Letters, abbreviations, proper nouns and conjugated forms: dropped.
  ['b', []], ['c', []], ['d', []], ['f', []], ['k', []], ['m', []],
  ['q', []], ['r', []], ['t', []], ['x', []], ['z', []], ['ó', []],
  ['as', []], ['be', []], ['ca', []], ['co', []], ['di', []], ['do', []],
  ['et', []], ['ex', []], ['fa', []], ['go', []], ['he', []], ['ja', []],
  ['ma', []], ['mm', []], ['na', []], ['pa', []], ['po', []], ['pp', []],
  ['re', []], ['so', []], ['ta', []], ['to', []], ['tv', []], ['ud', []],
  ['va', []], ['ve', []], ['we', []], ['xd', []], ['xi', []], ['app', []],
  ['bob', []], ['boy', []], ['che', []], ['dan', []], ['dió', []], ['don', []],
  ['era', []], ['fué', []], ['gil', []], ['haz', []], ['hey', []], ['ido', []],
  ['leo', []], ['man', []], ['mio', []], ['oye', []], ['pop', []], ['pre', []],
  ['san', []], ['son', []], ['sub', []], ['top', []], ['van', []], ['web', []],
  ['wow', []], ['alta', []], ['anda', []], ['anti', []], ['baja', []], ['basa', []],
  ['bebe', []], ['cabe', []], ['coca', []], ['coño', []], ['cuba', []], ['culo', []],
  ['dale', []], ['data', []], ['deja', []], ['dejo', []], ['diga', []], ['digo', []],
  ['dije', []], ['doña', []], ['echo', []], ['fría', []], ['full', []], ['gane', []],
  ['gran', []], ['hace', []], ['haya', []], ['info', []], ['jaja', []], ['jean', []],
  ['joda', []], ['juro', []], ['link', []], ['loca', []], ['luis', []], ['mail', []],
  ['mala', []], ['mata', []], ['mate', []], ['mato', []], ['mini', []], ['mira', []],
  ['miro', []], ['miss', []], ['nena', []], ['orto', []], ['paja', []], ['pedo', []],
  ['pega', []], ['play', []], ['poca', []], ['post', []], ['puta', []], ['puto', []],
  ['rica', []], ['rock', []], ['roja', []], ['rusa', []], ['ruso', []], ['saca', []],
  ['sale', []], ['sepa', []], ['show', []], ['siga', []], ['tira', []], ['toca', []],
  ['toma', []], ['tony', []], ['tour', []], ['tuit', []], ['tuya', []], ['vaya', []],
]);
