// Curated English glosses for Russian lemmas of four characters or fewer.
//
// These high-frequency short words are where the Wiktionary-derived pipeline is
// weakest: raw sense links drag in transliteration look-alikes (`и` → `yi`,
// `а` → `a`), grammatical labels (`раз` → `one`, `род` → `taxonomy`), and rare
// or idiomatic senses. A beginner cannot tell those apart from real
// translations, so they learn false associations.
//
// For every lemma here this map is authoritative: it fully replaces the
// Wiktionary glosses, both when regenerating the deck and when re-curating the
// committed file. Lists are kept to the senses a learner should actually
// associate with the Russian word. Lemmas longer than four characters are
// untouched.
import { curateCards as curateWithGlosses } from '../decks/curation.ts';

export const SHORT_WORD_MAX_LENGTH = 4;

export const SHORT_WORD_GLOSSES: ReadonlyMap<string, readonly string[]> = new Map<
  string,
  readonly string[]
>([
  // One character.
  ['а', ['and', 'but']],
  ['в', ['in', 'at', 'to']],
  ['и', ['and']],
  ['к', ['to', 'toward']],
  ['о', ['about']],
  ['с', ['with', 'from']],
  ['у', ['at', 'by']],
  ['я', ['i']],

  // Two characters.
  ['бы', ['would']],
  ['вы', ['you']],
  ['да', ['yes']],
  ['до', ['before', 'until']],
  ['же', ['indeed']],
  ['за', ['for', 'behind', 'after']],
  ['из', ['from', 'out of']],
  ['их', ['their', 'them']],
  ['кг', ['kg']],
  ['км', ['km']],
  ['ли', ['whether', 'if']],
  ['мм', ['mm']],
  ['мы', ['we']],
  ['на', ['on', 'at', 'to']],
  ['не', ['not']],
  ['ни', ['neither', 'nor']],
  ['но', ['but']],
  ['об', ['about']],
  ['ой', ['oh', 'ouch']],
  ['он', ['he', 'it']],
  ['от', ['from', 'away from']],
  ['по', ['on', 'along', 'by']],
  ['см', ['cm']],
  ['со', ['with', 'from']],
  ['та', ['that']],
  ['то', ['that', 'then']],
  ['ту', ['that']],
  ['ты', ['you']],
  ['ум', ['mind']],
  ['ус', ['moustache']],
  ['юг', ['south']],

  // Three characters.
  ['бар', ['bar']],
  ['бег', ['run']],
  ['без', ['without']],
  ['бог', ['god']],
  ['бок', ['side']],
  ['бык', ['bull']],
  ['ваш', ['your', 'yours']],
  ['век', ['century', 'age']],
  ['вес', ['weight']],
  ['вид', ['appearance', 'view', 'kind']],
  ['вор', ['thief']],
  ['вот', ['here']],
  ['все', ['everyone', 'all']],
  ['вуз', ['university']],
  ['газ', ['gas']],
  ['где', ['where']],
  ['гид', ['guide']],
  ['год', ['year']],
  ['гол', ['goal']],
  ['два', ['two']],
  ['для', ['for']],
  ['дно', ['bottom']],
  ['дом', ['house', 'home']],
  ['душ', ['shower']],
  ['его', ['his', 'its', 'him']],
  ['еда', ['food']],
  ['жир', ['fat']],
  ['зал', ['hall', 'gym']],
  ['зло', ['evil']],
  ['зуб', ['tooth']],
  ['или', ['or']],
  ['имя', ['name']],
  ['как', ['how', 'like', 'as']],
  ['кот', ['cat']],
  ['кто', ['who']],
  ['лес', ['forest', 'woods']],
  ['лоб', ['forehead']],
  ['лук', ['onion', 'bow']],
  ['май', ['may']],
  ['мир', ['world', 'peace']],
  ['мой', ['my', 'mine']],
  ['муж', ['husband']],
  ['мэр', ['mayor']],
  ['мяч', ['ball']],
  ['над', ['above', 'over']],
  ['наш', ['our', 'ours']],
  ['нет', ['no']],
  ['низ', ['bottom']],
  ['нож', ['knife']],
  ['нос', ['nose']],
  ['оба', ['both']],
  ['она', ['she']],
  ['они', ['they']],
  ['оно', ['it']],
  ['под', ['under', 'below']],
  ['пол', ['floor', 'half', 'sex']],
  ['пот', ['sweat']],
  ['при', ['at', 'by']],
  ['раз', ['time', 'once']],
  ['рис', ['rice']],
  ['род', ['kind', 'sort', 'generation']],
  ['рок', ['rock', 'fate']],
  ['рот', ['mouth']],
  ['ряд', ['row', 'series']],
  ['сад', ['garden']],
  ['сам', ['self', 'myself']],
  ['сок', ['juice']],
  ['сон', ['sleep', 'dream']],
  ['сто', ['hundred']],
  ['суп', ['soup']],
  ['сын', ['son']],
  ['сыр', ['cheese']],
  ['так', ['so', 'like that']],
  ['там', ['there']],
  ['тем', ['that']],
  ['тип', ['type', 'kind']],
  ['тот', ['that', 'those']],
  ['три', ['three']],
  ['тур', ['tour', 'round']],
  ['тут', ['here']],
  ['уже', ['already']],
  ['ура', ['hooray']],
  ['ухо', ['ear']],
  ['чай', ['tea']],
  ['час', ['hour']],
  ['чат', ['chat']],
  ['чей', ['whose']],
  ['чек', ['receipt', 'check']],
  ['чем', ['than']],
  ['что', ['what', 'that']],
  ['шаг', ['step']],
  ['шар', ['ball', 'sphere']],
  ['шея', ['neck']],
  ['шоу', ['show']],
  ['шум', ['noise']],
  ['эта', ['this']],
  ['это', ['this', 'that', 'it']],
  ['яма', ['pit', 'hole']],

  // Four characters.
  ['араб', ['arab']],
  ['балл', ['point', 'mark', 'grade']],
  ['банк', ['bank']],
  ['баня', ['bathhouse', 'banya']],
  ['бинт', ['bandage']],
  ['бить', ['beat', 'hit']],
  ['блин', ['pancake', 'blini']],
  ['блог', ['blog']],
  ['бокс', ['boxing']],
  ['боль', ['pain']],
  ['борщ', ['borscht']],
  ['брак', ['marriage', 'defect']],
  ['брат', ['brother']],
  ['быть', ['be']],
  ['ваза', ['vase']],
  ['веко', ['eyelid']],
  ['вера', ['faith', 'belief']],
  ['верх', ['top']],
  ['весы', ['scales']],
  ['весь', ['all', 'whole']],
  ['вещь', ['thing']],
  ['виза', ['visa']],
  ['вино', ['wine']],
  ['вкус', ['taste']],
  ['вниз', ['down', 'downwards']],
  ['внук', ['grandson']],
  ['вода', ['water']],
  ['враг', ['enemy']],
  ['врач', ['doctor']],
  ['вход', ['entrance']],
  ['гель', ['gel']],
  ['герб', ['coat of arms']],
  ['гимн', ['anthem', 'hymn']],
  ['глаз', ['eye']],
  ['гора', ['mountain']],
  ['град', ['hail']],
  ['грек', ['greek']],
  ['гриб', ['mushroom', 'fungus']],
  ['гром', ['thunder']],
  ['губа', ['lip']],
  ['даже', ['even']],
  ['дата', ['date']],
  ['дача', ['dacha', 'country house']],
  ['двор', ['yard', 'courtyard']],
  ['дело', ['matter', 'business', 'affair']],
  ['день', ['day']],
  ['диск', ['disk', 'disc']],
  ['дома', ['at home']],
  ['дочь', ['daughter']],
  ['друг', ['friend']],
  ['дума', ['thought', 'duma']],
  ['дура', ['fool']],
  ['духи', ['perfume']],
  ['дыня', ['melon']],
  ['дыра', ['hole']],
  ['дядя', ['uncle']],
  ['евро', ['euro']],
  ['если', ['if']],
  ['есть', ['eat', 'there is']],
  ['жаль', ['pity', 'sorry']],
  ['жара', ['heat']],
  ['жена', ['wife']],
  ['жест', ['gesture']],
  ['жить', ['live']],
  ['заяц', ['hare']],
  ['звук', ['sound']],
  ['зима', ['winter']],
  ['злой', ['evil', 'angry']],
  ['змея', ['snake']],
  ['знак', ['sign', 'mark']],
  ['зонт', ['umbrella']],
  ['зять', ['son-in-law']],
  ['игра', ['game', 'play']],
  ['идея', ['idea']],
  ['идти', ['go']],
  ['июль', ['july']],
  ['июнь', ['june']],
  ['кадр', ['frame', 'shot']],
  ['каша', ['porridge']],
  ['кило', ['kilo']],
  ['кино', ['movie', 'cinema']],
  ['клей', ['glue']],
  ['клуб', ['club']],
  ['ключ', ['key']],
  ['кожа', ['skin', 'leather']],
  ['коза', ['goat']],
  ['конь', ['horse']],
  ['корм', ['feed', 'fodder']],
  ['кофе', ['coffee']],
  ['кран', ['faucet', 'crane']],
  ['крем', ['cream']],
  ['круг', ['circle']],
  ['куда', ['where']],
  ['купе', ['compartment']],
  ['курс', ['course']],
  ['куст', ['bush']],
  ['лето', ['summer']],
  ['лечь', ['lie down']],
  ['лист', ['leaf', 'sheet']],
  ['литр', ['liter']],
  ['лить', ['pour']],
  ['лифт', ['elevator']],
  ['лицо', ['face', 'person']],
  ['лужа', ['puddle']],
  ['луна', ['moon']],
  ['лыжа', ['ski']],
  ['люди', ['people']],
  ['мало', ['little', 'few']],
  ['мама', ['mother', 'mom']],
  ['март', ['march']],
  ['матч', ['match']],
  ['мать', ['mother']],
  ['меню', ['menu']],
  ['метр', ['meter']],
  ['мода', ['fashion']],
  ['мозг', ['brain']],
  ['море', ['sea']],
  ['мост', ['bridge']],
  ['мочь', ['can', 'be able to']],
  ['мука', ['flour', 'torment']],
  ['мыло', ['soap']],
  ['мыть', ['wash']],
  ['мышь', ['mouse']],
  ['мясо', ['meat']],
  ['надо', ['must', 'need']],
  ['небо', ['sky', 'heaven']],
  ['ниже', ['below', 'lower']],
  ['нога', ['leg', 'foot']],
  ['ноль', ['zero']],
  ['ночь', ['night']],
  ['няня', ['nanny']],
  ['обед', ['lunch', 'dinner']],
  ['овощ', ['vegetable']],
  ['один', ['one']],
  ['окно', ['window']],
  ['опыт', ['experience', 'experiment']],
  ['орех', ['nut']],
  ['отец', ['father']],
  ['офис', ['office']],
  ['очки', ['glasses']],
  ['папа', ['dad', 'pope']],
  ['пара', ['pair', 'couple']],
  ['парк', ['park']],
  ['пена', ['foam']],
  ['петь', ['sing']],
  ['печь', ['bake', 'stove']],
  ['пиво', ['beer']],
  ['пить', ['drink']],
  ['план', ['plan']],
  ['плащ', ['raincoat', 'cloak']],
  ['плюс', ['plus']],
  ['пляж', ['beach']],
  ['пока', ['while', 'bye']],
  ['пора', ['time', 'season']],
  ['поэт', ['poet']],
  ['пояс', ['belt']],
  ['путь', ['way', 'path']],
  ['пыль', ['dust']],
  ['пять', ['five']],
  ['рана', ['wound']],
  ['рано', ['early']],
  ['рейс', ['flight', 'trip']],
  ['река', ['river']],
  ['речь', ['speech']],
  ['ритм', ['rhythm']],
  ['роза', ['rose']],
  ['роль', ['role']],
  ['рост', ['growth', 'height']],
  ['рука', ['hand', 'arm']],
  ['рыба', ['fish']],
  ['сайт', ['website']],
  ['сбор', ['collection', 'gathering']],
  ['свет', ['light']],
  ['свой', ['own']],
  ['себе', ['oneself']],
  ['себя', ['oneself']],
  ['секс', ['sex']],
  ['семь', ['seven']],
  ['сила', ['strength', 'force']],
  ['слог', ['syllable']],
  ['слон', ['elephant']],
  ['слух', ['hearing', 'rumor']],
  ['смех', ['laughter']],
  ['снег', ['snow']],
  ['соль', ['salt']],
  ['сорт', ['kind', 'sort', 'variety']],
  ['соус', ['sauce']],
  ['союз', ['union', 'conjunction']],
  ['спор', ['argument', 'dispute']],
  ['стих', ['verse', 'poem']],
  ['стол', ['table']],
  ['стоп', ['stop']],
  ['стук', ['knock']],
  ['стул', ['chair']],
  ['сухо', ['dryly']],
  ['суша', ['land']],
  ['сюда', ['here']],
  ['твой', ['your', 'yours']],
  ['тело', ['body']],
  ['тема', ['topic', 'theme']],
  ['темп', ['pace', 'tempo']],
  ['тень', ['shadow']],
  ['тест', ['test']],
  ['течь', ['flow', 'leak']],
  ['тигр', ['tiger']],
  ['тихо', ['quietly']],
  ['тоже', ['also', 'too']],
  ['торт', ['cake']],
  ['тост', ['toast']],
  ['труд', ['work', 'labor']],
  ['туда', ['there']],
  ['туча', ['cloud']],
  ['угол', ['corner', 'angle']],
  ['удар', ['blow', 'hit', 'strike']],
  ['ужин', ['supper', 'dinner']],
  ['укол', ['injection', 'prick']],
  ['урок', ['lesson']],
  ['утро', ['morning']],
  ['файл', ['file']],
  ['факс', ['fax']],
  ['финн', ['finn']],
  ['флаг', ['flag']],
  ['фото', ['photo']],
  ['фунт', ['pound']],
  ['хлеб', ['bread']],
  ['холл', ['hall', 'lobby']],
  ['хотя', ['although']],
  ['хрен', ['horseradish']],
  ['цвет', ['color', 'flower']],
  ['цель', ['goal', 'aim']],
  ['цена', ['price']],
  ['цент', ['cent']],
  ['цирк', ['circus']],
  ['часы', ['clock', 'watch']],
  ['чего', ['what']],
  ['член', ['member', 'limb']],
  ['чуть', ['a little', 'barely']],
  ['шарф', ['scarf']],
  ['шить', ['sew']],
  ['шкаф', ['cupboard', 'wardrobe']],
  ['щека', ['cheek']],
  ['этаж', ['floor', 'storey']],
  ['этот', ['this']],
  ['юбка', ['skirt']],
  ['юмор', ['humor']],
  ['юный', ['young']],
  ['язык', ['language', 'tongue']],
  ['яйцо', ['egg']],
  ['ясно', ['clearly']],
  ['ящик', ['box', 'drawer']],
]);

export function isShortWord(lemma: string): boolean {
  return [...lemma].length <= SHORT_WORD_MAX_LENGTH;
}

export function curatedGlossesFor(lemma: string): readonly string[] | null {
  return SHORT_WORD_GLOSSES.get(lemma) ?? null;
}

// Replaces every short lemma's cards with its curated glosses, preserving the
// position of the lemma's first occurrence. Longer lemmas are left untouched.
export function curateCards(cards: [string, string][]): [string, string][] {
  return curateWithGlosses(cards, SHORT_WORD_GLOSSES, SHORT_WORD_MAX_LENGTH);
}
